
enum
{
	ITEMID_ShieldCode								= 0x02040000,
	ITEMID_HairPotionCode							= 0x080C0000,
	ITEMID_HairPotionCode2							= 0x08110000,


	ITEMHDLRLOADID_ViperArmor						= 2,
	ITEMHDLRLOADID_DestroyerArmor					= 0,
	ITEMHDLRLOADID_PhoenixRobe						= 2,
};

struct HeadModelStruct
{
	DWORD										dwCode;
	DWORD										dwTier;
	char										* pszFile;
};

static HeadModelStruct saFighterHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\tmh-b01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\tmh-b01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\tmh_b01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\tmh-b01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\tmh-b01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\tmh-b02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\tmh-b02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\tmh_b02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\tmh-b02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\tmh-b02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\tmh-b03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\tmh-b03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\tmh_b03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\tmh-b03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\tmh-b03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\tmh-b04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\tmh-b04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\tmh_b04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\tmh-b04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\tmh-b04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\tmh-b05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\tmh-b05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\tmh_b05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\tmh-b05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\tmh-b05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\tmh-b06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\tmh-b06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\tmh_b06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\tmh-b06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\tmh-b06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\tmh-b07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\tmh-b07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\tmh_b07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\tmh-b07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\tmh-b07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\tmh-b08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\tmh-b08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\tmh_b08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\tmh-b08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\tmh-b08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\tmh-b09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\tmh-b09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\tmh_b09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\tmh-b09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\tmh-b09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\tmh-b10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\tmh-b10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\tmh_b10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\tmh-b10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\tmh-b10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\tmh-b11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\tmh-b11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\tmh_b11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\tmh-b11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\tmh-b11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\tmh-b12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\tmh-b12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\tmh_b12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\tmh-b12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\tmh-b12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\tmh-b13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\tmh-b13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\tmh_b13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\tmh-b13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\tmh-b13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-b19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-b20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-b21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-b22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-b23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hfighter_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hfighter_03.inf" },


	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-B25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-B99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhB-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\fsxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\fsxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhB14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhB15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhB16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhB17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhB30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhB31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhB32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaFS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Tmh-B27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatFS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatFS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatFS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatFS.inf" },
	{ ITEMID_SharinganEye, 0, "char\\tmABCD\\SharinganFS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairFS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_FS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_FS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgFS.inf"},
};

static HeadModelStruct saMechanicianHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Tmh-a01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Tmh-a01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Tmh_a01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Tmh-a01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Tmh-a01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Tmh-a02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Tmh-a02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Tmh_a02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Tmh-a02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Tmh-a02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Tmh-a03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Tmh-a03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Tmh_a03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Tmh-a03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Tmh-a03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Tmh-a04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Tmh-a04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Tmh_a04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Tmh-a04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Tmh-a04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Tmh-a05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Tmh-a05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Tmh_a05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Tmh-a05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Tmh-a05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Tmh-a06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Tmh-a06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Tmh_a06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Tmh-a06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Tmh-a06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Tmh-a07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Tmh-a07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Tmh_a07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Tmh-a07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Tmh-a07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Tmh-a08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Tmh-a08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Tmh_a08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Tmh-a08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Tmh-a08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Tmh-a09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Tmh-a09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Tmh_a09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Tmh-a09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Tmh-a09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Tmh-a10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Tmh-a10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Tmh_a10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Tmh-a10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Tmh-a10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Tmh-a11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Tmh-a11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Tmh_a11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Tmh-a11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Tmh-a11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Tmh-a12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Tmh-a12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Tmh_a12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Tmh-a12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Tmh-a12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Tmh-a13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Tmh-a13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Tmh_a13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Tmh-a13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Tmh-a13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-a19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-a20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-a21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-a22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-a23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hmech_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hmech_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-A25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-A99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhA-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\msxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\msxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhA14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhA15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhA16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhA17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhA30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhA31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhA32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaMS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Tmh-A27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatMS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatMS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatMS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatMS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairMS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_MS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_MS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgMS.inf"},
};

static HeadModelStruct saArcherHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Tfh-d01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Tfh-d01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Tfh_d01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Tfh-d01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Tfh-d01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Tfh-d02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Tfh-d02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Tfh_d02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Tfh-d02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Tfh-d02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Tfh-d03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Tfh-d03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Tfh_d03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Tfh-d03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Tfh-d03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Tfh-d04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Tfh-d04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Tfh_d04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Tfh-d04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Tfh-d04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Tfh-d05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Tfh-d05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Tfh_d05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Tfh-d05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Tfh-d05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Tfh-d06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Tfh-d06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Tfh_d06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Tfh-d06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Tfh-d06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Tfh-d07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Tfh-d07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Tfh_d07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Tfh-d07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Tfh-d07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Tfh-d08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Tfh-d08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Tfh_d08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Tfh-d08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Tfh-d08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Tfh-d09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Tfh-d09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Tfh_d09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Tfh-d09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Tfh-d09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Tfh-d10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Tfh-d10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Tfh_d10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Tfh-d10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Tfh-d10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Tfh-d11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Tfh-d11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Tfh_d11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Tfh-d11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Tfh-d11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Tfh-d12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Tfh-d12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Tfh_d12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Tfh-d12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Tfh-d12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Tfh-d13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Tfh-d13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Tfh_d13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Tfh-d13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Tfh-d13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tfh-d19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tfh-d20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tfh-d21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tfh-d22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tfh-d23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\harcher_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\harcher_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tfh-D25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tfh-D99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TfhD-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\asxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\asxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TfhD14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TfhD15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TfhD16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TfhD17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TfhD30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TfhD31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TfhD32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nAS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Tfh-D27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatAS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatAS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatAS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatAS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairAS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_AS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_AS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgAS.inf"},
};

static HeadModelStruct saPikemanHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Tmh-c01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Tmh-c01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Tmh_c01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\TmhC-01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Tmh-c01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Tmh-c02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Tmh-c02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Tmh_c02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\TmhC-02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Tmh-c02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Tmh-c03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Tmh-c03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Tmh_c03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\TmhC-03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Tmh-c03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Tmh-c04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Tmh-c04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Tmh_c04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\TmhC-04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Tmh-c04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Tmh-c05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Tmh-c05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Tmh_c05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\TmhC-05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Tmh-c05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Tmh-c06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Tmh-c06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Tmh_c06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\TmhC-06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Tmh-c06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Tmh-c07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Tmh-c07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Tmh_c07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\TmhC-07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Tmh-c07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Tmh-c08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Tmh-c08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Tmh_c08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\TmhC-08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Tmh-c08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Tmh-c09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Tmh-c09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Tmh_c09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\TmhC-09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Tmh-c09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Tmh-c10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Tmh-c10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Tmh_c10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\TmhC-10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Tmh-c10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Tmh-c11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Tmh-c11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Tmh_c11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\TmhC-11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Tmh-c11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Tmh-c12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Tmh-c12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Tmh_c12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\TmhC-12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Tmh-c12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Tmh-c13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Tmh-c13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Tmh_c13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\TmhC-13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Tmh-c13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tmh-c19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tmh-c20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tmh-c21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tmh-c22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tmh-c23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hpike_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hpike_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tmh-C25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tmh-C99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TmhC-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\psxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\psxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\TmhC14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\TmhC15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\TmhC16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\TmhC17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\TmhC30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\TmhC31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\TmhC32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaPS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Tmh-C27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatPS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatPS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatPS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatPS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairPS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_PS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_PS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgPS.inf"},
};

static HeadModelStruct saAtalantaHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Mfh-b01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Mfh-b01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Mfh_b01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Mfh-b01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Mfh-b01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Mfh-b02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Mfh-b02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Mfh_b02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Mfh-b02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Mfh-b02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Mfh-b03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Mfh-b03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Mfh_b03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Mfh-b03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Mfh-b03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Mfh-b04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Mfh-b04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Mfh_b04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Mfh-b04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Mfh-b04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Mfh-b05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Mfh-b05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Mfh_b05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Mfh-b05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Mfh-b05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Mfh-b06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Mfh-b06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Mfh_b06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Mfh-b06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Mfh-b06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Mfh-b07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Mfh-b07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Mfh_b07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Mfh-b07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Mfh-b07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Mfh-b08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Mfh-b08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Mfh_b08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Mfh-b08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Mfh-b08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Mfh-b09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Mfh-b09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Mfh_b09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Mfh-b09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Mfh-b09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Mfh-b10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Mfh-b10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Mfh_b10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Mfh-b10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Mfh-b10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Mfh-b11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Mfh-b11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Mfh_b11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Mfh-b11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Mfh-b11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Mfh-b12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Mfh-b12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Mfh_b12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Mfh-b12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Mfh-b12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Mfh-b13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Mfh-b13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Mfh_b13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Mfh-b13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Mfh-b13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mfh-b19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mfh-b20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mfh-b21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mfh-b22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mfh-b23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hatalanta_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hatalanta_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mfh-B25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mfh-B99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MfhB-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\ataxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\ataxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MfhB14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MfhB15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MfhB16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MfhB17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MfhB30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MfhB31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MfhB32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nATA.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Mfh-B27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatATA.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatATA.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatATA.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatATA.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairATA.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_ATA.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_ATA.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgATA.inf"},
};

static HeadModelStruct saKnightHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Mmh-a01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Mmh-a01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Mmh_a01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Mmh-a01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Mmh-a01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Mmh-a02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Mmh-a02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Mmh_a02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Mmh-a02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Mmh-a02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Mmh-a03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Mmh-a03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Mmh_a03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Mmh-a03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Mmh-a03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Mmh-a04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Mmh-a04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Mmh_a04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Mmh-a04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Mmh-a04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Mmh-a05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Mmh-a05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Mmh_a05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Mmh-a05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Mmh-a05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Mmh-a06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Mmh-a06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Mmh_a06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Mmh-a06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Mmh-a06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Mmh-a07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Mmh-a07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Mmh_a07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Mmh-a07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Mmh-a07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Mmh-a08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Mmh-a08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Mmh_a08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Mmh-a08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Mmh-a08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Mmh-a09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Mmh-a09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Mmh_a09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Mmh-a09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Mmh-a09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Mmh-a10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Mmh-a10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Mmh_a10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Mmh-a10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Mmh-a10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Mmh-a11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Mmh-a11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Mmh_a11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Mmh-a11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Mmh-a11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Mmh-a12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Mmh-a12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Mmh_a12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Mmh-a12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Mmh-a12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Mmh-a13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Mmh-a13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Mmh_a13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Mmh-a13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Mmh-a13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-a19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-a20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-a21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-a22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-a23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hknight_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hknight_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-A25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-A99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhA-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\ksxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\ksxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MmhA14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MmhA15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MmhA16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MmhA17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MmhA30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MmhA31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MmhA32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaKS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Mmh-A27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatKS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatKS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatKS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatKS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairKS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_KS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_KS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgKS.inf"},
};

static HeadModelStruct saMagicianHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Mmh-d01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Mmh-d01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Mmh_d01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Mmh-d01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Mmh-d01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Mmh-d02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Mmh-d02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Mmh_d02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Mmh-d02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Mmh-d02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Mmh-d03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Mmh-d03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Mmh_d03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Mmh-d03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Mmh-d03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Mmh-d04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Mmh-d04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Mmh_d04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Mmh-d04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Mmh-d04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Mmh-d05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Mmh-d05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Mmh_d05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Mmh-d05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Mmh-d05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Mmh-d06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Mmh-d06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Mmh_d06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Mmh-d06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Mmh-d06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Mmh-d07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Mmh-d07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Mmh_d07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Mmh-d07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Mmh-d07d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Mmh-d08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Mmh-d08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Mmh_d08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Mmh-d08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Mmh-d08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Mmh-d09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Mmh-d09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Mmh_d09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Mmh-d09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Mmh-d09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Mmh-d10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Mmh-d10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Mmh_d10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Mmh-d10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Mmh-d10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Mmh-d11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Mmh-d11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Mmh_d11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Mmh-d11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Mmh-d11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Mmh-d12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Mmh-d12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Mmh_d12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Mmh-d12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Mmh-d12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Mmh-d13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Mmh-d13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Mmh_d13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Mmh-d13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Mmh-d13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-d19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-d20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-d21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-d22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-d23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hmage_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hmage_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-D25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-D99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhD-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\mgxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\mgxmas.inf" },
	
	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MmhD14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MmhD15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MmhD16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MmhD17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MmhD30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MmhD31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MmhD32.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaMG.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Mmh-D27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatMG.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatMG.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatMG.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatMG.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairMG.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_MG.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_MG.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgMG.inf"},
};

static HeadModelStruct saPriestessHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Mfh-c01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Mfh-c01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Mfh_c01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Mfh-c01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Mfh-c01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Mfh-c02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Mfh-c02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Mfh_c02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Mfh-c02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Mfh-c02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Mfh-c03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Mfh-c03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Mfh_c03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Mfh-c03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Mfh-c03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Mfh-c04.inf" },
	{ ITEMID_HairPotionD, 1, "char\\tmABCD\\Mfh-c04a.inf" },
	{ ITEMID_HairPotionD, 2, "char\\tmABCD\\Mfh_c04b.inf" },
	{ ITEMID_HairPotionD, 3, "char\\tmABCD\\Mfh-c04c.inf" },
	{ ITEMID_HairPotionD, 4, "char\\tmABCD\\Mfh-c04d.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Mfh-c05.inf" },
	{ ITEMID_HairPotionE, 1, "char\\tmABCD\\Mfh-c05a.inf" },
	{ ITEMID_HairPotionE, 2, "char\\tmABCD\\Mfh_c05b.inf" },
	{ ITEMID_HairPotionE, 3, "char\\tmABCD\\Mfh-c05c.inf" },
	{ ITEMID_HairPotionE, 4, "char\\tmABCD\\Mfh-c05d.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Mfh-c06.inf" },
	{ ITEMID_HairPotionF, 1, "char\\tmABCD\\Mfh-c06a.inf" },
	{ ITEMID_HairPotionF, 2, "char\\tmABCD\\Mfh_c06b.inf" },
	{ ITEMID_HairPotionF, 3, "char\\tmABCD\\Mfh-c06c.inf" },
	{ ITEMID_HairPotionF, 4, "char\\tmABCD\\Mfh-c06d.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Mfh-c07.inf" },
	{ ITEMID_HairPotionG, 1, "char\\tmABCD\\Mfh-c07a.inf" },
	{ ITEMID_HairPotionG, 2, "char\\tmABCD\\Mfh_c07b.inf" },
	{ ITEMID_HairPotionG, 3, "char\\tmABCD\\Mfh-c07c.inf" },
	{ ITEMID_HairPotionG, 4, "char\\tmABCD\\Mfh-C007d.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Mfh-c08.inf" },
	{ ITEMID_HairPotionH, 1, "char\\tmABCD\\Mfh-c08a.inf" },
	{ ITEMID_HairPotionH, 2, "char\\tmABCD\\Mfh_c08b.inf" },
	{ ITEMID_HairPotionH, 3, "char\\tmABCD\\Mfh-c08c.inf" },
	{ ITEMID_HairPotionH, 4, "char\\tmABCD\\Mfh-c08d.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Mfh-c09.inf" },
	{ ITEMID_HairPotionI, 1, "char\\tmABCD\\Mfh-c09a.inf" },
	{ ITEMID_HairPotionI, 2, "char\\tmABCD\\Mfh_c09b.inf" },
	{ ITEMID_HairPotionI, 3, "char\\tmABCD\\Mfh-c09c.inf" },
	{ ITEMID_HairPotionI, 4, "char\\tmABCD\\Mfh-c09d.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Mfh-c10.inf" },
	{ ITEMID_HairPotionJ, 1, "char\\tmABCD\\Mfh-c10a.inf" },
	{ ITEMID_HairPotionJ, 2, "char\\tmABCD\\Mfh_c10b.inf" },
	{ ITEMID_HairPotionJ, 3, "char\\tmABCD\\Mfh-c10c.inf" },
	{ ITEMID_HairPotionJ, 4, "char\\tmABCD\\Mfh-c10d.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Mfh-c11.inf" },
	{ ITEMID_HairPotionK, 1, "char\\tmABCD\\Mfh-c11a.inf" },
	{ ITEMID_HairPotionK, 2, "char\\tmABCD\\Mfh_c11b.inf" },
	{ ITEMID_HairPotionK, 3, "char\\tmABCD\\Mfh-c11c.inf" },
	{ ITEMID_HairPotionK, 4, "char\\tmABCD\\Mfh-c11d.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Mfh-c12.inf" },
	{ ITEMID_HairPotionL, 1, "char\\tmABCD\\Mfh-c12a.inf" },
	{ ITEMID_HairPotionL, 2, "char\\tmABCD\\Mfh_c12b.inf" },
	{ ITEMID_HairPotionL, 3, "char\\tmABCD\\Mfh-c12c.inf" },
	{ ITEMID_HairPotionL, 4, "char\\tmABCD\\Mfh-c12d.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Mfh-c13.inf" },
	{ ITEMID_HairPotionM, 1, "char\\tmABCD\\Mfh-c13a.inf" },
	{ ITEMID_HairPotionM, 2, "char\\tmABCD\\Mfh_c13b.inf" },
	{ ITEMID_HairPotionM, 3, "char\\tmABCD\\Mfh-c13c.inf" },
	{ ITEMID_HairPotionM, 4, "char\\tmABCD\\Mfh-c13d.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mfh-c19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mfh-c20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mfh-c21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mfh-c22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mfh-c23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hpriestess_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hpriestess_03.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mfh-C25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mfh-C99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MfhC-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\prsxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\prsxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\MfhC14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\MfhC15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\MfhC16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\MfhC17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\MfhC30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\MfhC31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\MfhC32.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nPRS.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Mfh-C27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatPRS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatPRS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatPRS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatPRS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairPRS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_PRS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_PRS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgPRS.inf"},
};

static HeadModelStruct saAssassinHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Tfh-e01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Tfh-e01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Tfh_e01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Tfh-e01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Tfh-e01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Tfh-e02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Tfh-e02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Tfh_e02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Tfh-e02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Tfh-e02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Tfh-e03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Tfh-e03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Tfh_e03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Tfh-e03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Tfh-e03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Tfh-e04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Tfh-e05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Tfh-e06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Tfh-e07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Tfh-e08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Tfh-e09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Tfh-e10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Tfh-e11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Tfh-e12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Tfh-e13.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Tfh-e19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Tfh-e20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Tfh-e21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Tfh-e22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Tfh-e23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hassassin_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hassassin_03.inf" },

	{ ITEMID_WitchHat, 0, "char\\tmABCD\\ar0nASS.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Tfh-E25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Tfh-E99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\TfhE-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\assxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\assxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\Tfh-E14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\Tfh-E15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\Tfh-E16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\Tfh-E17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\Tfh-E30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\Tfh-E31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\Tfh-E32.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Tfh-E27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatASS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatASS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatASS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatASS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairASS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_ASS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_ASS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgASS.inf"},
};

static HeadModelStruct saShamanHeadModel[]
{
	{ ITEMID_HairPotionA, 0, "char\\tmABCD\\Mmh-e01.inf" },
	{ ITEMID_HairPotionA, 1, "char\\tmABCD\\Mmh-e01a.inf" },
	{ ITEMID_HairPotionA, 2, "char\\tmABCD\\Mmh_e01b.inf" },
	{ ITEMID_HairPotionA, 3, "char\\tmABCD\\Mmh-e01c.inf" },
	{ ITEMID_HairPotionA, 4, "char\\tmABCD\\Mmh-e01d.inf" },
	{ ITEMID_HairPotionB, 0, "char\\tmABCD\\Mmh-e02.inf" },
	{ ITEMID_HairPotionB, 1, "char\\tmABCD\\Mmh-e02a.inf" },
	{ ITEMID_HairPotionB, 2, "char\\tmABCD\\Mmh_e02b.inf" },
	{ ITEMID_HairPotionB, 3, "char\\tmABCD\\Mmh-e02c.inf" },
	{ ITEMID_HairPotionB, 4, "char\\tmABCD\\Mmh-e02d.inf" },
	{ ITEMID_HairPotionC, 0, "char\\tmABCD\\Mmh-e03.inf" },
	{ ITEMID_HairPotionC, 1, "char\\tmABCD\\Mmh-e03a.inf" },
	{ ITEMID_HairPotionC, 2, "char\\tmABCD\\Mmh_e03b.inf" },
	{ ITEMID_HairPotionC, 3, "char\\tmABCD\\Mmh-e03c.inf" },
	{ ITEMID_HairPotionC, 4, "char\\tmABCD\\Mmh-e03d.inf" },
	{ ITEMID_HairPotionD, 0, "char\\tmABCD\\Mmh-e04.inf" },
	{ ITEMID_HairPotionE, 0, "char\\tmABCD\\Mmh-e05.inf" },
	{ ITEMID_HairPotionF, 0, "char\\tmABCD\\Mmh-e06.inf" },
	{ ITEMID_HairPotionG, 0, "char\\tmABCD\\Mmh-e07.inf" },
	{ ITEMID_HairPotionH, 0, "char\\tmABCD\\Mmh-e08.inf" },
	{ ITEMID_HairPotionI, 0, "char\\tmABCD\\Mmh-e09.inf" },
	{ ITEMID_HairPotionJ, 0, "char\\tmABCD\\Mmh-e10.inf" },
	{ ITEMID_HairPotionK, 0, "char\\tmABCD\\Mmh-e11.inf" },
	{ ITEMID_HairPotionL, 0, "char\\tmABCD\\Mmh-e12.inf" },
	{ ITEMID_HairPotionM, 0, "char\\tmABCD\\Mmh-e13.inf" },
	{ ITEMID_HairPotionN, 0, "char\\tmABCD\\Mmh-e19.inf" },
	{ ITEMID_HairPotionO, 0, "char\\tmABCD\\Mmh-e20.inf" },
	{ ITEMID_HairPotionP, 0, "char\\tmABCD\\Mmh-e21.inf" },
	{ ITEMID_HairPotionQ, 0, "char\\tmABCD\\Mmh-e22.inf" },
	{ ITEMID_HairPotionR, 0, "char\\tmABCD\\Mmh-e23.inf" },
	{ ITEMID_HairPotionS, 0, "char\\tmABCD\\hshaman_02.inf" },
	{ ITEMID_HairPotionT, 0, "char\\tmABCD\\hshaman_03.inf" },

	{ ITEMID_CartolaHat, 0, "char\\tmABCD\\CartolaSH.inf" },

	{ ITEMID_SheepHat, 0, "char\\tmABCD\\Mmh-E25.inf" },
	{ ITEMID_GiraffeHat, 0, "char\\tmABCD\\Mmh-E99.inf" },
	{ ITEMID_SoccerHat, 0, "char\\tmABCD\\MmhE-18t.inf" },
	{ ITEMID_XMasGreenHat, 0, "char\\tmABCD\\shxmasg.inf" },
	{ ITEMID_XMasRedHat, 0, "char\\tmABCD\\shxmas.inf" },

	{ ITEMID_BigHeadHappyness, 0, "char\\tmABCD\\Mmh-E14t.inf" },
	{ ITEMID_BigHeadLove, 0, "char\\tmABCD\\Mmh-E15t.inf" },
	{ ITEMID_BigHeadSadness, 0, "char\\tmABCD\\Mmh-E16t.inf" },
	{ ITEMID_BigHeadShyness, 0, "char\\tmABCD\\Mmh-E17t.inf" },
	{ ITEMID_BigHeadAngry, 0, "char\\tmABCD\\Mmh-E30.inf" },
	{ ITEMID_BigHeadSurprised, 0, "char\\tmABCD\\Mmh-E31.inf" },
	{ ITEMID_BigHeadSensual, 0, "char\\tmABCD\\Mmh-E32.inf" },
	{ ITEMID_HalloweenHat, 0, "char\\tmABCD\\Mmh-E27.inf" },
	{ ITEMID_TuttiFruttiHat, 0, "char\\tmABCD\\CarnivalHatSS.inf" },
	{ ITEMID_EasterHat, 0, "char\\tmABCD\\EasterHatSS.inf" },
	{ ITEMID_ChemistHat, 0, "char\\tmABCD\\AlchemistHatSS.inf" },
	{ ITEMID_PatronumHat, 0, "char\\tmABCD\\ChiwenHatSS.inf" },
	{ITEMID_IceHair, 0, "char\\tmABCD\\IceHairSS.inf"},
	{ITEMID_SamuraiHair, 0, "char\\tmABCD\\SamuraiHair_SS.inf"},
	{ITEMID_GoldenHopyHat, 0, "char\\tmABCD\\G_Hopt_SS.inf"},
	{ITEMID_ObscureHat, 0, "char\\tmABCD\\DarkdgSS.inf"},
};

